// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Cases.proto

package Cases

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Case struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Infectedtype         string   `protobuf:"bytes,4,opt,name=infectedtype,proto3" json:"infectedtype,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbfbff0eae9a6294, []int{0}
}

func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (m *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(m, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Case) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Case) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Case) GetInfectedtype() string {
	if m != nil {
		return m.Infectedtype
	}
	return ""
}

func (m *Case) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ServerResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbfbff0eae9a6294, []int{1}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Case)(nil), "Case")
	proto.RegisterType((*ServerResponse)(nil), "ServerResponse")
}

func init() {
	proto.RegisterFile("Cases.proto", fileDescriptor_cbfbff0eae9a6294)
}

var fileDescriptor_cbfbff0eae9a6294 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x76, 0x4e, 0x2c, 0x4e,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x6a, 0x62, 0xe4, 0x62, 0x01, 0xf1, 0x85, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21,
	0x29, 0x2e, 0x8e, 0x9c, 0xfc, 0xe4, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x26, 0xb0, 0x38, 0x9c,
	0x2f, 0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x9e, 0x2a, 0xc1, 0x0c, 0x14, 0x66, 0x0d, 0x02, 0x31, 0x85,
	0x94, 0xb8, 0x78, 0x32, 0xf3, 0xd2, 0x52, 0x93, 0x4b, 0x52, 0x53, 0x4a, 0x2a, 0x0b, 0x52, 0x25,
	0x58, 0xc0, 0x3a, 0x50, 0xc4, 0x84, 0x44, 0xb8, 0x58, 0x8b, 0x4b, 0x12, 0x4b, 0x52, 0x25, 0x58,
	0xc1, 0x92, 0x10, 0x8e, 0x92, 0x0e, 0x17, 0x5f, 0x70, 0x6a, 0x51, 0x59, 0x6a, 0x51, 0x50, 0x6a,
	0x71, 0x41, 0x7e, 0x5e, 0x31, 0xd8, 0xe6, 0x22, 0x28, 0x1b, 0xea, 0x22, 0x38, 0xdf, 0xc8, 0x84,
	0x8b, 0x33, 0xb8, 0xa4, 0x34, 0xa5, 0x12, 0xec, 0x6c, 0x75, 0x2e, 0x4e, 0x9f, 0xcc, 0xe2, 0x12,
	0xb0, 0x97, 0x84, 0x58, 0xf5, 0x40, 0xb4, 0x14, 0xbf, 0x1e, 0xaa, 0x69, 0x4a, 0x0c, 0x1a, 0x8c,
	0x49, 0x6c, 0x60, 0xff, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xff, 0x2e, 0x40, 0xfe,
	0x00, 0x00, 0x00,
}
